# -*- coding: utf-8 -*-
"""load_squad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiAH3JCD6m5_vcB_vtFQkwJRMfRF3iog
"""

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

!pip install datasets
from datasets import load_dataset
import os
#gives access to hugging face dataset
#hugging face is the github of ML models

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Install & load
!pip install datasets
from datasets import load_dataset
import os

# Load SQuAD
dataset = load_dataset("squad")

# Set paths
folder_for_documents = '/content/drive/MyDrive/cost-optimized-rag/data/documents'
folder_for_queries = '/content/drive/MyDrive/cost-optimized-rag/data/queries'

# Create folders
os.makedirs(folder_for_documents, exist_ok=True)
os.makedirs(folder_for_queries, exist_ok=True)

# Save 20 documents
for i in range(20):
    one_item = dataset['train'][i]
    title = one_item['title']
    text = one_item['context']
    filename = f'{folder_for_documents}/doc_{i:02d}.txt'
    file = open(filename, 'w')
    file.write(f"Title: {title}\n\n{text}")
    file.close()

print("✅ Created 20 documents")

# Save 30 simple queries
csv_filename = f'{folder_for_queries}/test_queries.csv'
csv_file = open(csv_filename, 'w')
csv_file.write('query_id,query,complexity,ground_truth\n')

for i in range(30):
    one_item = dataset['train'][i]
    question = one_item['question']
    answer = one_item['answers']['text'][0]
    csv_file.write(f'{i},"{question}",simple,"{answer}"\n')  # All labeled "simple"

csv_file.close()
print("✅ Created 30 simple queries")
print("\n✅ Done! Check Google Drive")